# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160311_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constructor',
            new_name='Generator',
        ),
    ]
